version: "3.9"
services:
  web:
    build:
      context: ./web
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
