version: "3.9"
services:
  web:
    build:
      context: ./web
    ports:
      - "3000:80"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./server/data  # path to directory to store dataset files and task files
        target: /app/data
      - type: bind
        source: ./server/out
        target: /app/out
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    runtime: nvidia
